<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <!--page generated by WebAcappella-->
    <!-- 2016-07-31T15:20:39 *******************************-->
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7;IE=EmulateIE9" />
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <meta name="generator" content="WebAcappella 4.6.21  ecommerce (WIN) #583b" />
    <title></title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="<?php echo base_url("static/css/materialize.css"); ?>" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="<?php echo base_url("static/css/style.css"); ?>" type="text/css" rel="stylesheet" media="screen,projection"/>
    <style type="text/css">
        body {
            /* margin-left: 0px;
            margin-top: 0px;
            margin-right: 0px;
            margin-bottom: 0px; */
            background-image: url('/static/site/img/bg_site.png');
            background-repeat: no-repeat;
            background-color: #e9e9e9;
            background-position: initial;
            background-size: contain;
        }
    </style>

    <style>
    /*
      CSS para o materialized
     */
     body {
      display: flex;
      min-height: 100vh;
      flex-direction: column;
      /* #background: #FFC1C1; */
    }
    main {
     flex: 1 0 auto;
    }
    </style>

    <style type="text/css">
		/*
			Especial css site
		 */

    	.no-shadown{
    		box-shadow: none;
    	}

    	#header-site{
    		background-repeat: no-repeat;
    		/* background-image: url('/static/site/header-bg.png?v=2z2dm85x8kjpkyf'); */
    	}

    	.menu-site {
    		font-weight: bold;
    	}
    </style>
    <!-- <link rel="stylesheet" type="text/css" href="/static/site/wa_global_style.css" />
    <script type="text/javascript" src="/static/site/jquery.js?v=86c"></script>
    <script type="text/javascript">
        var waJSQuery = jQuery.noConflict();
    </script>
    <script type="text/javascript" src="/static/site/webacappella_core.js?v=1ups"></script> -->
    <!--[if lte IE 8]><script type="text/javascript"  src="/static/site/excanvas.js?v=1f2a"></script>
<![endif]-->
    <!--[if lte IE 8]><script type="text/javascript"  src="/static/site/webacappella_patch_ie8.js?v=tc5"></script>
<![endif]-->
    <!-- <script type="text/javascript">
        document.write("\u003cscript type='text/javascript'  src='/static/site/wa_site_global_settings.js?v=2wv75o5x8k7shfy" + urlSuffixe(1) + "'>\u003c/script>");
    </script>
    <script type="text/javascript" src="/static/site/jquery.mousewheel.js?v=use"></script>
    <link href="/static/site/webacappe lla.css?v=10nl" rel="stylesheet" type="text/css" media="all" /> -->
    <!--[if lte IE 7]>
<link href="webacappella_ie.css?v=1tjn" rel="stylesheet" type="text/css" media="all"/>
<![endif]-->
<!--     <script type="text/javascript" src="/static/site/webacappella_tools.js?v=blf"></script>
<script type="text/javascript">
    waJSQuery(function() {
        initializeWA_JQuery()
    });
</script>
<script type="text/javascript">
    var waWebFontDescription = {
        families: []
    }
</script> -->

</head>
<main>
<body>
<div class="container" style="height: 200px;">
    <div class="row">
        <div class="col s12 l3">
        	<div class="" id="header-site">
        		<nav class="transparent no-shadown">
        			<img class="responsive-img" src="/static/site/logo_site.png" alt="" />
        		</nav>
        	</div>
        </div>
        <div class="col s12 l9">
        	<nav class="transparent no-shadown" role="navigation">
        	    <div class="nav-wrapper">
        	      <ul class="left hide-on-med-and-down">
        	        <li <?php if($view == 'home'): ?> class="active" <?php endif; ?> ><a class="menu-site" href="<?php echo base_url("home"); ?>">Home</a></li>
        	        <li <?php if($view == 'produtos'): ?> class="active" <?php endif; ?> ><a class="menu-site" href="<?php echo base_url("produtos/page"); ?>">Produtos</a></li>
        	        <li <?php if($view == 'servicos'): ?> class="active" <?php endif; ?> ><a class="menu-site" href="<?php echo base_url("servicos"); ?>">Serviços</a></li>
        	        <li <?php if($view == 'orcamentos'): ?> class="active" <?php endif; ?> ><a class="menu-site" href="<?php echo base_url("orcamentos"); ?>">Orçamentos</a></li>
        	        <li <?php if($view == 'dicas'): ?> class="active" <?php endif; ?> ><a class="menu-site" href="<?php echo base_url("orcamentos"); ?>">Dicas</a></li>
        	        <li <?php if($view == 'contato'): ?> class="active" <?php endif; ?> ><a class="menu-site" href="<?php echo base_url("contato"); ?>">Contato</a></li>
        	      </ul>

        	      <ul id="nav-mobile" class="side-nav">
        	        <li <?php if($view == 'home'): ?> class="active" <?php endif; ?> ><a class="menu-site" href="<?php echo base_url("home"); ?>">Home</a></li>
        	        <li <?php if($view == 'produtos'): ?> class="active" <?php endif; ?> ><a class="menu-site" href="<?php echo base_url("produtos/page"); ?>">Produtos</a></li>
        	        <li <?php if($view == 'servicos'): ?> class="active" <?php endif; ?> ><a class="menu-site" href="<?php echo base_url("servicos"); ?>">Serviços</a></li>
        	        <li <?php if($view == 'orcamentos'): ?> class="active" <?php endif; ?> ><a class="menu-site" href="<?php echo base_url("orcamentos"); ?>">Orçamentos</a></li>
        	        <li <?php if($view == 'dicas'): ?> class="active" <?php endif; ?> ><a class="menu-site" href="<?php echo base_url("orcamentos"); ?>">Dicas</a></li>
        	        <li <?php if($view == 'contato'): ?> class="active" <?php endif; ?> ><a class="menu-site" href="<?php echo base_url("contato"); ?>">Contato</a></li>
        	      </ul>
        	      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons green-text">menu</i></a>
        	    </div>
        	</nav>
        </div>
    </div>
</div>    
